server: 
  port: 8080
spring: 
  application:
    name: biz-consumer
feign:
  hystrix: 
    enabled: true
hystrix: 
  command:
    default:
  execution: 
    isolation: 
      thread:
        timeoutInMilliseconds: 100   
      circuitBreaker:  
        requestVolumeThreshold: 3 
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.22.1.56:8761/eureka/
logging: 
  level: 
    com.netflix: DEBUG