server: 
  port: 8777
spring: 
  application:
    name: biz-provider
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing 
feign:
  hystrix: 
    enabled: true
    command: 
      default: 
        execution: 
          isolation:
            thread:
              timeoutInMilliseconds: 1000000   
            circuitBreaker:  
              requestVolumeThreshold: 200
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.22.1.56:8761/eureka/
    register-with-eureka: true
logging: 
  level: 
    com.netflix: DEBUG

   
---
spring: 
  profiles: dev
server: 
  port: 8070
  

feign:
  hystrix: 
    enabled: true
    command: 
    default: 
      execution: 
        isolation:
          thread:
            timeoutInMilliseconds: 1000000   
          circuitBreaker:  
            requestVolumeThreshold: 200
hystrix: 
  command: 
    default: 
      execution: 
        isolation:
          thread:
            timeoutInMilliseconds: 1000000   
          circuitBreaker:  
            requestVolumeThreshold: 200
---
spring: 
  profiles: test
    
