server: 
<<<<<<< HEAD
  port: 8777
=======
  port: 8080
>>>>>>> new version
spring: 
  application:
    name: biz-consumer
feign:
  hystrix: 
    enabled: true
hystrix: 
  command:
<<<<<<< HEAD
    HelloClient#hello():
  execution: 
    isolation:
=======
    default
  execution: 
    isolation: 
>>>>>>> new version
      thread:
        timeoutInMilliseconds: 100   
      circuitBreaker:  
        requestVolumeThreshold: 3 
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.22.1.56:8761/eureka/
logging: 
  level: 
    com.netflix: DEBUG